<?php

/*
 * This file is part of Kazist Framework.
 * (c) Dedan Irungu <irungudedan@gmail.com>
 *  For the full copyright and license information, please view the LICENSE file that was distributed with this source code.
 * 
 */

/**
 * Description of RatesController
 *
 * @author sbc
 */

namespace Payments\Rates\Code\Controllers;

defined('KAZIST') or exit('Not Kazist Framework');

use Kazist\Controller\BaseController;
use Payments\Rates\Code\Models\RatesModel;

class RatesController extends BaseController {

    public function addAction() {

        $factory = new KazistFactory();
        $factory->enqueueMessage('Rates is Only Auto Generated By System', 'error');
        return $this->redirectToRoute('admin.payments.transactions');
    }

    public function editAction() {

        $factory = new KazistFactory();
        $factory->enqueueMessage('Rates is Only Auto Generated By System', 'error');
        return $this->redirectToRoute('admin.payments.transactions');
    }

    public function crongeneratefileAction() {

        $this->model = new RatesModel();
        $this->model->generateRatesFile();

        return $this->redirectToRoute('admin.payments.transactions');
    }

}
